# Generated by Django 4.2.3 on 2023-08-27 12:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Property",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=50)),
                ("description", models.TextField()),
                ("address", models.CharField(max_length=250)),
                ("area", models.CharField(max_length=250)),
                (
                    "purpose",
                    models.CharField(
                        choices=[("For Rent", "For Rent"), ("For Sale", "For Sale")],
                        max_length=15,
                    ),
                ),
                ("price", models.IntegerField()),
                ("main_image", models.ImageField(upload_to="")),
                ("image_2", models.ImageField(blank=True, upload_to="")),
                ("image_3", models.ImageField(blank=True, upload_to="")),
                ("image_4", models.ImageField(blank=True, upload_to="")),
                (
                    "is_negotiable",
                    models.CharField(
                        choices=[("Y", "YES"), ("N", "NO")], default="N", max_length=3
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PropertyCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="PropertyFeature",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("feature_name", models.CharField(max_length=40)),
                ("feature_value", models.CharField(max_length=40)),
                (
                    "property",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="realtor.property",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="property",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="realtor.propertycategory",
            ),
        ),
    ]
